In [25]:
import pandas as pd
import json
# command line : jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10
# keep redundancy
# 1st & second order jsons

# Workflow connections

In [12]:
#            wf_id |     wf_updated      | in_id |      in_tool      | in_tool_v | out_id |     out_tool      | out_tool_v | published | deleted | has_errors
#		    -------+---------------------+-------+-------------------+-----------+--------+-------------------+----------------------------------------------
#		         3 | 2013-02-07 16:48:00 |     5 | Grep1             | 1.0.1     |     12 |                   |            |    f      |    f    |    f
#		         3 | 2013-02-07 16:48:00 |     6 | Cut1              | 1.0.1     |      7 | Remove beginning1 | 1.0.0      |    f      |    f    |    f
#		         3 | 2013-02-07 16:48:00 |     7 | Remove beginning1 | 1.0.0     |      5 | Grep1             | 1.0.1      |    f      |    f    |    f
#		         3 | 2013-02-07 16:48:00 |     8 | addValue          | 1.0.0     |      6 | Cut1              | 1.0.1      |    t      |    f    |    f
#		         3 | 2013-02-07 16:48:00 |     9 | Cut1              | 1.0.1     |      7 | Remove beginning1 | 1.0.0      |    f      |    f    |    f
#		         3 | 2013-02-07 16:48:00 |    10 | addValue          | 1.0.0     |     11 | Paste1            | 1.0.0      |    t      |    f    |    f
#		         3 | 2013-02-07 16:48:00 |    11 | Paste1            | 1.0.0     |      9 | Cut1              | 1.0.1      |    f      |    f    |    f
#		         3 | 2013-02-07 16:48:00 |    11 | Paste1            | 1.0.0     |      8 | addValue          | 1.0.0      |    t      |    t    |    f
#		         4 | 2013-02-07 16:48:00 |    13 | cat1              | 1.0.0     |     18 | addValue          | 1.0.0      |    t      |    f    |    f
#		         4 | 2013-02-07 16:48:00 |    13 | cat1              | 1.0.0     |     20 | Count1            | 1.0.0      |    t      |    t    |    f


#746139 rows × 11 columns
colnames = ['wf_id', 'wf_updated', 'in_id', 'in_tool', 'in_tool_v', 'out_id', 'out_tool', 'out_tool_v', 'published', 'deleted', 'has_errors']
# nrows = 74 : subset with 3 workflows: 3, 4 & 5
# max id : 50779, min : id 3
df = pd.read_csv("/Users/kaoutar/Documents/galaxy_tool_recommendation-master/data/worflow-connection-20-04.tsv", 
                 names=colnames, header = None, delimiter="\t")
#df

In [18]:
df[(df["published"]=="t") & (df["deleted"]=="t")]

,wf_id,wf_updated,in_id,in_tool,in_tool_v,out_id,out_tool,out_tool_v,published,deleted,has_errors
240,12,2013-02-07 17:04:38.354863,180,cat1,1.0.0,189,barchart_gnuplot,1.0.0,t,t,f
242,12,2013-02-07 17:04:38.354863,181,bedtools_intersectBed,NaN,183,wc_gnu,1.0.0,t,t,f
244,12,2013-02-07 17:04:38.354863,182,bedtools_intersectBed,NaN,184,sort1,1.0.1,t,t,f
246,12,2013-02-07 17:04:38.354863,183,wc_gnu,1.0.0,185,addValue,1.0.0,t,t,f
248,12,2013-02-07 17:04:38.354863,184,sort1,1.0.1,186,cshl_awk_tool,NaN,t,t,f
...,...,...,...,...,...,...,...,...,...,...,...
719143,46318,2020-03-07 17:07:09.007751,671715,NaN,NaN,671722,toolshed.g2.bx.psu.edu/repos/bgruening/augustu...,3.2.3+galaxy1,t,t,f
719144,46318,2020-03-07 17:07:09.007751,671715,NaN,NaN,671721,toolshed.g2.bx.psu.edu/repos/iuc/snap_training...,2013_11_29+galaxy1,t,t,f
719145,46318,2020-03-07 17:07:09.007751,671715,NaN,NaN,671720,toolshed.g2.bx.psu.edu/repos/iuc/maker/maker/2...,2.31.10,t,t,f
719146,46318,2020-03-07 17:07:09.007751,671715,NaN,NaN,671719,toolshed.g2.bx.psu.edu/repos/iuc/busco/busco/3...,3.0.2+galaxy1,t,t,f
719147,46318,2020-03-07 17:07:09.007751,671715,NaN,NaN,671718,toolshed.g2.bx.psu.edu/repos/simon-gladman/fas...,1.0.0,t,t,f

In [24]:
df["out_tool"].unique().size

3251

In [5]:

workflows_dict={}

for id in range(3, 50779):
    #print(id)
    workflow={}
    id_df= df.loc[df['wf_id'] == id]
    in_keys=list(set(id_df['in_tool'].values))
    in_keys=[item for item in in_keys if not(pd.isnull(item)) == True]
    
    #print(in_keys)
    #print()
    #print("*************************************************************************************")
    #print()
    
    for in_key in in_keys:
        
        #print(in_key)
        
        in_values=[]
        in_values = list(set(id_df[id_df['in_tool']==in_key]['out_tool'].tolist()))
        #print(in_values)
        #print()
        #print("*************************************************************************************")
        #print()
        
        workflow[in_key] = in_values
        workflows_dict[id] = workflow    
        #print(workflow)


    #print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")

#print(workflows_dict)

In [6]:
    
with open("/Users/kaoutar/Documents/galaxy_tool_recommendation-master/my_data/workflow_connections.json", "w") as jf:
    json.dump(workflows_dict, jf, indent=4)